### ISSUE TITLE
consumerWorker.StopAndWait无法退出

### ISSUE THREAD

**Issue by luowuf** [aliyun/aliyun-log-go-sdk#101]
![image](https://user-images.githubusercontent.com/10563618/96697220-4064e480-13be-11eb-80a5-ce14dafc01cd.png)

一直输出错误

**Comment by marlonfan** [comment]
process方法不要panic 正确处理退出  就好了. 我这边好像是这样

**Comment by shabicheng** [comment]
楼上正解，你的processor函数一直挂掉
