### ISSUE TITLE
外网消费数据一段时间后停住

### ISSUE THREAD

**Issue by zhaolun7** [aliyun/aliyun-log-go-sdk#118]
按照demo进行消费，结果直接打印
在外网消费一分钟不到就会停止
在阿里云内网机器上消费则正常？

另外，无论内网外网，速度都提不起来，内网4m/s，外网3m/s，请问是什么原因？
我的联系方式 471018885@qq.com

**Comment by zhaolun7** [comment]
![image](https://user-images.githubusercontent.com/16096787/105431679-0e02a600-5c91-11eb-8a09-d50d42350bbe.png)

**Comment by shabicheng** [comment]
消费速度和Shard数据产生的量有关系，数据产生少的话，消费的速度肯定也对应的少
