### ISSUE TITLE
panic: runtime error: index out of range [5] with length 5

### ISSUE THREAD

**Issue by ace2021** [aliyun/aliyun-log-go-sdk#120]
panic: runtime error: index out of range [5] with length 5

goroutine 1384870 [running]:
github.com/aliyun/aliyun-log-go-sdk.(*LogContent).MarshalTo(0xc0345deb40, 0xc0362d7efa, 0x5, 0x5, 0xa, 0x1b, 0x0)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/log.pb.go:265 +0x306
github.com/aliyun/aliyun-log-go-sdk.(*Log).MarshalTo(0xc0337b7600, 0xc0362d7edf, 0x20, 0x20, 0xa1, 0x5bedf, 0x0)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/log.pb.go:303 +0x1d7
github.com/aliyun/aliyun-log-go-sdk.(*LogGroup).MarshalTo(0xc02a2131f0, 0xc03627c000, 0x5beff, 0x5beff, 0x40d28a, 0xb08500, 0xb7b700)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/log.pb.go:373 +0x17a
github.com/aliyun/aliyun-log-go-sdk.(*LogGroup).Marshal(0xc02a2131f0, 0xc8abe0, 0xc02a2131f0, 0x7f92d05f99a8, 0xc02a2131f0, 0x522901)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/log.pb.go:356 +0x7a
github.com/gogo/protobuf/proto.Marshal(0xc8abe0, 0xc02a2131f0, 0x0, 0xc032e66e00, 0x0, 0x200, 0x0)
        /go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_marshal.go:2945 +0x213
github.com/aliyun/aliyun-log-go-sdk.(*LogStore).PutLogs(0xc01b9b82a0, 0xc02a2131f0, 0x0, 0x0)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/log_store.go:187 +0x8b
github.com/aliyun/aliyun-log-go-sdk.(*Client).PutLogs(0xc00010e800, 0xbc12ad, 0xf, 0xbc24a9, 0x10, 0xc02a2131f0, 0xc0341dec90, 0x40be7f)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/client_store.go:82 +0x6b
github.com/aliyun/aliyun-log-go-sdk/producer.(*IoWorker).sendToServer(0xc0000b6aa0, 0xc0112dc540, 0xc00003ce70)
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/producer/io_worker.go:50 +0xdc2
created by github.com/aliyun/aliyun-log-go-sdk/producer.(*IoThreadPool).start
        /go/pkg/mod/github.com/aliyun/aliyun-log-go-sdk@v0.1.18/producer/io_thread_pool.go:57 +0x119

**Comment by shabicheng** [comment]
更新到 v0.1.19 版本，这个版本修复了producer在多个并发情况下可能出现crash的问题
