### ISSUE TITLE
GenerateLog 使用的map占用内存高

### ISSUE THREAD

**Issue by sado0823** [aliyun/aliyun-log-go-sdk#122]
GenerateLog 使用的map占用内存高有啥解决方案吗

**Comment by sado0823** [comment]
![image](https://user-images.githubusercontent.com/51654192/116783423-494b1700-aac1-11eb-8615-09934c090d7a.png)

**Comment by sado0823** [comment]
![image](https://user-images.githubusercontent.com/51654192/116783543-d2fae480-aac1-11eb-8cfc-e30f811163e3.png)
现在是用writer的方式接入, pprof如上.
如果直接map然后用map generate log, 就是pprof看到map内存一直很高

**Comment by sado0823** [comment]
写数据

参考put_log.go

这里展示了用sdk中原生的API接口去发送数据简单示例，但是我们不推荐用API直接向logstore写入数据，推荐使用SDK 中提供的producer 包向logstore 写入数据，自动压缩数据并且提供安全退出机制，不会使数据丢失。

有example吗, 我看readme里面又说不要直接发送, LogGroup不就是直接发送的吗

**Comment by shabicheng** [comment]
@sado0823   https://github.com/aliyun/aliyun-log-go-sdk/blob/master/example/producer/performance_test_demo.go
参考这个Demo

**Comment by sado0823** [comment]
ok

**Comment by sado0823** [comment]
@shabicheng ok 多谢
