### ISSUE TITLE
md5计算 开销过高的问题

### ISSUE THREAD

**Issue by Kuri-su** [aliyun/aliyun-log-go-sdk#138]
我看到 SDK 发送 HTTP 请求的时候会计算一个 Body 的 MD5 ，在一些小 Body 的场景里面可能没什么感觉， 

但是我们的场景下面， 可能每一个Body 都是 1Mbyte 的 package ， 这样算 MD5 会给我们造成很大的 CPU 开销（比我们业务使用的 CPU 还要多）

所以想请问这里Header 里的 Content-MD5 是否是强制选项，如果不是强制选项， 能否提供一个 Option 让用户关闭这里的 MD5 计算，

**Comment by shabicheng** [comment]
这个 issue非常好，ContentMD5是非必须的字段，可以去掉

**Comment by shabicheng** [comment]
POST请求必须计算MD5，因为还需要通过MD5再计算签名，主要是防止body被篡改，这个是所有SDK的feature，没办法更改

**Comment by Kuri-su** [comment]
很多时候我一个日志其实我根本不关心是否 body 被修改.....但我却花费巨大的资源在这里算 MD5

能不能推动下你们 SLS 部分把这个改成可选, 我理解 logtail 部分关注日志完整性, 但是我在 sdk 调用传递的场景上面可能没有那么关注完整性, 而且我们这里是直接走internal 的域名内网传输......
