### ISSUE TITLE
一个sdk http连接复用设置不合理引发的问题

### ISSUE THREAD

**Issue by Gitforxuyang** [aliyun/aliyun-log-go-sdk#155]
go version: 1.13

aliyun-log-go-sdk version: v0.1.12

问题描述：发现sdk在较多的请求时不停的创建、关闭http连接，造成大量的dns解析和一些其它性能消耗

问题原因：经过排查，发现sdk用的是官方默认的DefaultTransport，而DefaultTransport里面没有配置MaxIdleConnsPerHost，所以最终DefaultMaxIdleConnsPerHost生效，而默认的DefaultMaxIdleConnsPerHost=2，则最终的结果是，一旦空闲连接数超过2，其它结束请求的连接就会被关闭，造成的现象就是sdk在不停创建、关闭连接，http的连接复用机制形同虚设。

建议：规范sdk的defaultHttpClient的配置，给出合理的默认值，最好提供方法让使用者可以自行设置http client

烦请有看到此issue麻烦尽快给个回复，因为对于我们这边算是线上问题了，如果官方没法很快给出修复版本，我们可能要自己fork代码去修改此问题

**Comment by shabicheng** [comment]
感谢认可，您的需求在我们之前的规划中，我们将提高优先级，即将在下个版本中增加对自定义Client的支持

**Comment by shabicheng** [comment]
> 

已经发布，v0.1.31 https://github.com/aliyun/aliyun-log-go-sdk/issues/155#issuecomment-1110915682

**Comment by shabicheng** [comment]
https://github.com/aliyun/aliyun-log-go-sdk/blob/v0.1.31/client_interface.go#L45

**Comment by Gitforxuyang** [comment]
牛！

**Comment by Gitforxuyang** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/16128584/165669734-893a6c38-7359-4c33-b931-7ae893c1d06f.png">

ConsumerClient里的client没法修改

**Comment by shabicheng** [comment]
@Gitforxuyang 不好意思没注意你们用的是consumer，请使用最新Tag：
https://github.com/aliyun/aliyun-log-go-sdk/releases/tag/v0.1.33
