### ISSUE TITLE
Use log-go-sdk GetLogStore return "errorCode": "ParameterInvalid", and http extend authorization

### ISSUE THREAD

**Issue by his1devil** [aliyun/aliyun-log-go-sdk#16]
![image](https://user-images.githubusercontent.com/1657654/44957812-077d0380-af09-11e8-84a7-53c28a9bf500.png)
cannot find the errorCode in docs，ID & secret are right, stuck here, someone help ? thanks ~~

**Comment by his1devil** [comment]
Case solved.

**Comment by FSudong** [comment]
请问怎么处理的

**Comment by FSudong** [comment]
> Case solved.

请问怎么解决的呀？？
