### ISSUE TITLE
日志组件bug，如果有option.LogFileName配置，option.IsJsonType 判断写反了

### ISSUE THREAD

**Issue by xmpx310** [aliyun/aliyun-log-go-sdk#162]
`
github.com/aliyun/aliyun-log-go-sdk@v0.1.35/consumer/worker.go

// This function is used to initialize the global log configuration
func logConfig(option LogHubConfig) log.Logger {
	var logger log.Logger

	if option.LogFileName == "" {
		if option.IsJsonType {
			logger = log.NewJSONLogger(log.NewSyncWriter(os.Stdout))
		} else {
			logger = log.NewLogfmtLogger(log.NewSyncWriter(os.Stdout))
		}
	} else {
          //判断写反了
		if option.IsJsonType {
			logger = log.NewLogfmtLogger(initLogFlusher(option))
		} else {
			logger = log.NewJSONLogger(initLogFlusher(option))
		}
	}
`

**Comment by crimson-gao** [comment]
fixed
