### ISSUE TITLE
ClientInterface 中定义了一个未导出的方法 listEtlMeta。

### ISSUE THREAD

**Issue by Richard1ybb** [aliyun/aliyun-log-go-sdk#177]
ClientInterface interface {
	...
	listEtlMeta(project string, etlMetaName, etlMetaKey, etlMetaTag string, offset, size int) (total int, count int, etlMeta []*EtlMeta, err error)
	ListEtlMeta(project string, etlMetaName string, offset, size int) (total int, count int, etlMetaList []*EtlMeta, err error)
	...
}

`ClientInterface` 中定义了一个未导出的方法 `listEtlMeta`, 这个方法既无法让外部访问，还会导致mock `ClientInterface`时，无法实现这个interface。
因为`listEtlMeta`这个方法无法让外部访问，所以接口去去掉这个方法也是向前兼容的。

**Comment by crimson-gao** [comment]
#289
