### ISSUE TITLE
若心跳包超时，消费者会被杀掉。有什么方法能够检测到消费者down了，然后定期重新拉起

### ISSUE THREAD

**Issue by Nightfury12366** [aliyun/aliyun-log-go-sdk#221]

**Comment by wxybear** [comment]
使用上可以调整超时时间
另一方面，需要重新拉起消费者指的是？即使心跳包超时，只是不分配shard吧，你的消费者进程退出了嘛

**Comment by Nightfury12366** [comment]
背景如下：
假设	我启动了一个消费者consumerWorker：
```
consumerWorker := consumerLibrary.InitConsumerWorkerWithCheckpointTracker(option, process)
consumerWorker.Start() 
```

一段时间后，远端sls由于某些原因无法访问，consumerWorker因为心跳包超时，被杀死了。但是又过了一段时间，远端的sls恢复了，但是我的理解是消费者consumerWorker无法自动起来？需要再次手动调用consumerWorker.Start() 才能再次将其拉起么。

**Comment by wxybear** [comment]
应该不是的，worker不会被杀死，只是server端会把本该分配给这个worker的数据shard分配给其他worker，这个worker还在，等到重新有心跳了，server会重新分配

**Comment by starjun** [comment]
https://github.com/aliyun/aliyun-log-go-sdk/pull/181

这个分支解决上述问题了
