### ISSUE TITLE
producer/README.md的文档有函数名称单词错误

### ISSUE THREAD

**Issue by vic111** [aliyun/aliyun-log-go-sdk#269]
原文：
provider := sls.NewStaticCredentailsProvider(os.Getenv("AccessKeyID"), os.Getenv("AccessKeySecret"), "")
这行文档里的NewStaticCredentailsProvider的函数名
与代码里的NewStaticCredentialsProvider的函数
Credentials的 tail和tial这块不匹配拼写错误

**Comment by crimson-gao** [comment]
谢谢反馈，已修复

**Comment by jeepc** [comment]
https://github.com/aliyun/aliyun-log-go-sdk/blob/master/producer/README.md 这里面没有修复
