### ISSUE TITLE
log_store.go 533

### ISSUE THREAD

**Issue by wxjeek** [aliyun/aliyun-log-go-sdk#29]
uri := fmt.Sprintf("/logstores/%s?%s", s.Name, urlVal.Encode())

uri编码把+编码成%2B在request请求处又把%编码成%25导致服务端获取参数失败获取不到日志信息
 改成
	uri := fmt.Sprintf("/logstores/%v?type=log&topic=%v&from=%v&to=%v&query=%v&line=%v&offset=%v&reverse=%v", s.Name, topic, from, to, queryExp, maxLineNum, offset, reverse)

**Comment by shabicheng** [comment]
最新的版本已经解决了该问题，请下载最新版本使用
