### ISSUE TITLE
missing http extend header key : x-log-date

### ISSUE THREAD

**Issue by freemking** [aliyun/aliyun-log-go-sdk#31]
go版本：go1.11.4
代码版本 f7ccbaf 
调用Client.GetLogStore(ProjectName,LogStoreName)返回如下错误：

GetLogStore fail, err:{
    "httpCode": 400,
    "errorCode": "MissingParameter",
    "errorMessage": "missing http extend header key : x-log-date",
    "requestID": "5CDE2D1C85674B717132BBB4"
}

**Comment by xuxiaoahang2018** [comment]
你好，经过测试，代码版本 f7ccbaf 中GetLogStore接口可以正常使用，本次发布的新版本作为一个单独的包并没有修改原sdk中的代码，建议查看是否发送过程中报文被截断，可以重试几次查看一下调用结果。
