### ISSUE TITLE
依赖项 github.com/golang/glog 注册了 -v 的命令行参数，导致我的程序不能启动

### ISSUE THREAD

**Issue by shinny-chengzhi** [aliyun/aliyun-log-go-sdk#33]
glog 在 init 时注册了 -v 的命令行参数
https://github.com/aliyun/aliyun-log-go-sdk/blob/32935d02e7232bc87cbb2550e886f20a4306ec0a/vendor/github.com/golang/glog/glog.go#L401
我的程序也使用了 -v，导致import aliyun-log-go-sdk 后程序无法启动，报:
panic: run_ef flag redefined: v

**Comment by szyhf** [comment]
fork下来把glog删了吧……我也被这个东西烦死了……

**Comment by shabicheng** [comment]
新版本已经去掉glog依赖
