### ISSUE TITLE
bug. 用 consumer  提示    "Unauthorized\",\n  denied by sts or ram,  

### ISSUE THREAD

**Issue by tx991020** [aliyun/aliyun-log-go-sdk#38]
配置参数没问题，用 pull log的 能拉日志。 用comsumer 的 sdk 报错
evel=warn time=2019-08-08T08:04:25.149421Z caller=heart_beat.go:72 msg="send heartbeat error" error="{\n    \"httpCode\": 401,\n    \"errorCode\": \"Unauthorized\",\n    \"errorMessage\": \"denied by sts or ram, action: log:ConsumerGroupHeartBeat, resource: acs:log:cn-hangzhou:1595139653552356:project/guanghe-hub/logstore/order-flow/consumergroup/order2Group\",\n    \"requestID\": \"5D4BD78964ED3D851E02493F\"\n}"

**Comment by xuxiaoahang2018** [comment]
看报错是因为请求心跳接口权限不足导致，但是可以正常拉日志说明ak 应该是有部分权限的，使用消费组账号需要授予以下权限，请参考文档：https://help.aliyun.com/document_detail/28998.html?spm=a2c4g.11186623.6.925.2e165c8fqeSJOJ#title-exi-bpl-5c9
