### ISSUE TITLE
怎样提快消费者的拉取时间。

### ISSUE THREAD

**Issue by tx991020** [aliyun/aliyun-log-go-sdk#40]
shardId %v processing works sucess 2
level=info time=2019-08-13T09:55:17.171182Z caller=heart_beat.go:79 heartbeatresult="[0 1 2]" get="[0 1 2]"
level=info time=2019-08-13T09:55:37.261906Z caller=heart_beat.go:79 heartbeatresult="[0 1 2]" get="[0 1 2]"
level=info time=2019-08-13T09:55:57.369808Z caller=heart_beat.go:79 heartbeatresult="[0 1 2]" get="[0 1 2]"
level=info time=2019-08-13T09:56:17.484075Z caller=heart_beat.go:79 heartbeatresult="[0 1 2]" get="[0 1 2]"

用消费者 才 消费了 100条就一直发heartbeat，  太慢了。 感觉 还 直接用sdk 拉取快，怎么加快拉取速度？

**Comment by tx991020** [comment]
好几分钟拉不到一条，时间里面有几十万，这是什么原因？

**Comment by shabicheng** [comment]
@xuxiaoahang2018 看下这个问题  @tx991020  可以加一下钉钉群聊一下细节 
![image](https://user-images.githubusercontent.com/1451095/62937075-10a36f80-bdfe-11e9-8c02-d42bd77ad95e.png)

**Comment by tx991020** [comment]
这群是 客户群，没人 解决问题。
