### ISSUE TITLE
go module 支持

### ISSUE THREAD

**Issue by mofadeyunduo** [aliyun/aliyun-log-go-sdk#46]
我觉得需要支持 go module 进行版本管理，这个加起来应该很简单也没有风险

**Comment by willsdu** [comment]
今天更新发现vendor里面这个包又套了个vendor

**Comment by mofadeyunduo** [comment]
没有人去跟进这个事情吗？2019年，go 1.13 都 release 了，项目还不用标准化版本管理吗？

**Comment by shabicheng** [comment]
各位，go module 目前已经支持，由于需要兼容老的go版本，go vendor还会继续支持
