### ISSUE TITLE
建议修改示例代码

### ISSUE THREAD

**Issue by mofadeyunduo** [aliyun/aliyun-log-go-sdk#49]
直接复制代码跑，并不能跑起来，查文档也没什么可以参考的文档。只能看源码，才发现为什么获取 Project 失败，如何注册 Project。

https://github.com/aliyun/aliyun-log-go-sdk/blob/master/example/loghub/loghub_sample.go
```
projects, count, total, err := util.Client.ListProjectV2(offset, 100)
```

这个样例代码太不友好了，需要填写的配置最好显示声明，而不是默认从 os.GetEnv 获取数据（这谁能知道...？）

**Comment by xuxiaoahang2018** [comment]
示例代码版本较老，近期已经在更新示例代码部分，下个版本会替换掉老版本的simple.
