### ISSUE TITLE
但是因为每次sendLog接口调用都要通过GenerateLog方法序列化生成日志，性能非常低，推荐用户自己使用go sdk中原生的创建sls.Log的接口

### ISSUE THREAD

**Issue by cjl3080434008** [aliyun/aliyun-log-go-sdk#50]
这个怎么理解，最近准备使用这个sdk进行推送，怕有性能问题

**Comment by Goclis** [comment]
`GenerateLog` 方法使用上比较简单，但是做了一层转换（根据传入的参数构造出最终用于发送的 `sls.Log` 对象），有一定的性能开销（事实上不大）。

如果追求最佳性能的话，建议是手动构造 `sls.Log` 对象，可以参考这段[示例代码](https://github.com/aliyun/aliyun-log-go-sdk/blob/d3a95d13616a4e6bd230af106d7abfb2f68a0aab/example/loghub/loghub_sample.go#L70)。

**Comment by cjl3080434008** [comment]
好的 多谢 @Goclis
