### ISSUE TITLE
关于util.Client.GetLogs查询的数目不对问题

### ISSUE THREAD

**Issue by ShineJstar** [aliyun/aliyun-log-go-sdk#51]
`response, err := util.Client.GetLogs(utils.PROJECT, utils.LOGSTORE, "", startTime.Unix(), endTime.Unix(), “event:login | select uid, tm”, int64(50), int64(0), false)`
使用查询util.Client.GetLogs方法查询时设置参数maxLineNum=50，offset=0，但返回结果response.Count始终是100，response.Logs长度也是100，也就是说maxLineNum设置的参数无效？
注：在控制台查询日志总条数：342  查询状态：结果精确  扫描行数:342  查询时间:2ms
按照API参考文档SDK接口方法返回正确的Count应该是342，Logs长度是50吧？是我用法不对还是确实存在这个bug？
期待你的回复，谢谢

**Comment by shabicheng** [comment]
1.  如果使用SQL，分页模式是使用select的limit语法，外层的offset，lines不生效。相关文档可以参考 https://help.aliyun.com/document_detail/89994.html?spm=5176.11065259.1996646101.searchclickresult.ed44638c9mpjvV&aly_as=CS5u0mdS
2. 返回的总数代码实际返回的日志数，并不是查询的日志总数，一般查询日志总数需要用GetHistograms
