### ISSUE TITLE
认证错误提示

### ISSUE THREAD

**Issue by jmdkina** [aliyun/aliyun-log-go-sdk#61]
{\n    \"httpCode\": 400,\n    \"errorCode\": \"ParameterInvalid\",\n    \"errorMessage\": \"http extend authorization : SLS :RkHUjBySHIyT+Ok1xbCAgZZmoJ8= pair is invalid\",\n    \"requestID\": \"5E0347FB434FEAF15313FEF0\"\n}
这个回复大概是什么错误，producer_simple_demo.c这个文件，只改了必要的参数的测试结果, c 语言版本的已经测试过没有问题

**Comment by shabicheng** [comment]
fixed

**Comment by FSudong** [comment]
所以是怎么fix的？？

**Comment by FSudong** [comment]
> fixed

请问 怎么解决的呀？？

**Comment by RonaldinhoL** [comment]
同问什么原因啊
