### ISSUE TITLE
arm32架构CPU运行producer_simple_demo示例程序出现panic

### ISSUE THREAD

**Issue by sanallen** [aliyun/aliyun-log-go-sdk#64]
Go版本：1.10.3
CPU型号：armv7l 32位架构

崩溃信息：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x14cd8]

goroutine 1 [running]:
sync/atomic.addUint64(0x110ce1f4, 0x7b, 0x0, 0x78aa60, 0x110ce180)
        /usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/aliyun/aliyun-log-go-sdk/producer.(*LogAccumulator).addLogToProducerBatch(0x10f196d0, 0x7d7a0b, 0xe, 0x7d86a1, 0xf, 0x0, 0x0, 0x7cf97b, 0x5, 0x7d33fb, ...)
        /usr/local/gopath/src/github.com/aliyun/aliyun-log-go-sdk/producer/log_accumulator.go:67 +0x668
github.com/aliyun/aliyun-log-go-sdk/producer.(*Producer).SendLog(0x110c1020, 0x7d7a0b, 0xe, 0x7d86a1, 0xf, 0x7cf97b, 0x5, 0x7d33fb, 0x9, 0x11102140, ...)
        /usr/local/gopath/src/github.com/aliyun/aliyun-log-go-sdk/producer/producer.go:137 +0xb0

经过排查是因为对结构体里面的部分字段使用了atomic.AddInt64操作，而字段没有保证8字节对齐导致的程序崩溃问题。
初步的解决方案是暂时先将受影响的结构体字段放在结构体的前面部分

**Comment by sanallen** [comment]
#65 合并请求已提交，please review it

**Comment by mofadeyunduo** [comment]
我也遇到这个问题了，GOARCH=arm GOOS=linux，编译出来在这种类型上机器必定出问题

**Comment by sanallen** [comment]
> 我也遇到这个问题了，GOARCH=arm GOOS=linux，编译出来在这种类型上机器必定出问题

可以参考我提交的合并请求，https://github.com/aliyun/aliyun-log-go-sdk/pull/65

**Comment by shabicheng** [comment]
fixed https://github.com/aliyun/aliyun-log-go-sdk/commit/a84225cff033f9c62240cc735c34db489b4952cf
