### ISSUE TITLE
用sdk中原生的API接口并发5000写日志，内存达到2.7G，且不释放

### ISSUE THREAD

**Issue by shanfengchu** [aliyun/aliyun-log-go-sdk#66]
官方提供的示例，调用sdk中原生的API接口 util.Client.PutLogs(util.ProjectName, util.LogStoreName, loggroup)，并发5000写日志，内存达到2.7G，且不释放。

**Comment by xuxiaoahang2018** [comment]
1.请问日志最终是否写入成功？未成功是否有报错？还是启动后程序后夯住无报错也未成功写入？
2.每个shard每秒写入次数及流量有限制，详情参考 https://help.aliyun.com/document_detail/92571.html

**Comment by shanfengchu** [comment]
> 1.请问日志最终是否写入成功？未成功是否有报错？还是启动后程序后夯住无报错也未成功写入？
> 2.每个shard每秒写入次数及流量有限制，详情参考 https://help.aliyun.com/document_detail/92571.html

5000条日志绝大部分写入成功，服务端有少量报错
{
    "httpCode": -1,
    "errorCode": "ClientError",
    "errorMessage": "Post http://gaodun-dev.cn-hangzhou.log.aliyuncs.com/logstores/dev-app-gcommunity: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
    "requestID": ""
}
压测条件是服务程序启动后，用ab压测工具，压测服务的写日志性能。ab -n 5000 -c 5000 url(服务端的url接口)
