### ISSUE TITLE
用producer示例并发5000写日志，内存达到218M，但是内存不释放...

### ISSUE THREAD

**Issue by shanfengchu** [aliyun/aliyun-log-go-sdk#67]
用官方example中提供的producer示例并发5000写日志，内存达到218M，但是内存不释放...
由于自己的服务是不断接收消息打印日志的，producerInstance := producer.InitProducer(producerConfig)，在producerInstance.Start()，后并发5000写日志，内存达到218M，经过多次压测并发5000写日志，内存几乎没有增加，但是内存还是没释放......

**Comment by cupen** [comment]
这是 go 的 feature., 偶尔几次 OOM 都是小意思啦.
https://github.com/golang/go/issues/30333
https://github.com/golang/go/issues/36398

按里边说的:
export GODEBUG=madvdontneed=1
然后把 go 升级到 1.14 看看.
