### ISSUE TITLE
该如何处理错误, 才能保证 consumer 不重复, 不遗漏?

### ISSUE THREAD

**Issue by cupen** [aliyun/aliyun-log-go-sdk#69]
我的需求是这样:
读取 aliyun 日志的数据实时导入到关系型数据库中做进一步的数据分析, 无论进程崩溃, 还是数据库挂了, 都需要保证不重复, 不遗漏. 

做到以上, 需要:
1. 数据库事务, 保证日志批量插入是原子性的(已经满足).
2. 阿里云日志需要支持"消费进度" , 保证程序即便崩溃重启, 也能根据上一次的进度继续.

看下面示例代码和说明, 似乎这个消费进度保存在 aliyun 日志服务端.
https://github.com/aliyun/aliyun-log-go-sdk/tree/master/consumer
https://yq.aliyun.com/articles/693820

参照这个示例代码, 它要求我"如果日志消费失败, 不能跳出 process 方法, 要一直重试, ". 
对此我有疑问:
1.  如果是一些不可控的 panic 导致跳出 process 后会发生什么?  还能否"不重复,不遗漏"?
2.  在我一直消费失败并无限重试的情况下, 执行 StopAndWait 后重启进程又会发生什么, 还能否"不重复,不遗漏"?

```golang
func process(shardId int, logGroupList *sls.LogGroupList) string {
   for {
      err := func(shardId int, logGroupList *sls.LogGroupList) error {
          // 在这个函数当中去写具体的消费逻辑，如果消费失败，返回自定义的error
            return nil
      }(shardId,logGroupList)
      if err != nil{
         // 当捕获到消费失败的error以后只要重复继续执行消费逻辑即可，不要跳出process方法。
         continue
      }else{
         // 消费成功的话，跳出循环，process方法执行完毕，会继续拉取数据进行下次消费。
         break
      }
   }
   return "" // 不需要重置检查点情况下，请返回空字符串，如需要重置检查点，请返回需要重置的检查点游标。
}
```

**Comment by xuxiaoahang2018** [comment]
1.当消费函数发生panic 的情况下，消费组只能做到数据不遗漏，无法保证不重复。
2. 在消费过程中数据拉取是以日志组loggroup为单位进行拉取，拉取下来一个日志组可能包含1000条日志(数据), 在处理这批数据的过程中，例如处理到第500条，如果process这个函数panic ，则会重新运行该process, （会重复处理前500条数据）。假如整个程序崩溃, 下次重启消费组会从上一个检查点获取数据后执行任务。可能会有部分数据重复处理，但一定不会丢失。
3. 关于检查点，消费组会每隔一定时间去保存检查点（当前消费到的时间点），可以在源代码中搜索defaultFlushCheckPointIntervalSec 。

**Comment by cupen** [comment]
收到, 感谢回答.
这正是我期望的, 重复的问题已经用数据库事务解决了, 保证 loggroup 要么全部成功, 全部失败.
