### ISSUE TITLE
sample producer运行问题

### ISSUE THREAD

**Issue by maxmonkey950** [aliyun/aliyun-log-go-sdk#70]
文档上面说变量存在于config.go中，即使里面配置了，sample里面producer运行时，依旧报错缺少akid、aksecret、endpoint等变量。仔细看了之后在sample/producerdemo主函数中根本就没引用config.go 所在的util包。使用os.getenv获取不到变量。故修改如下。         （go新手，如果有误当我没说- -！）
![image](https://user-images.githubusercontent.com/46515596/76482424-0fe3c200-644f-11ea-8ec8-fca686080a19.png)

**Comment by shabicheng** [comment]
fixed, using env
