### ISSUE TITLE
internal server error,no avaliable shard

### ISSUE THREAD

**Issue by TankyH** [aliyun/aliyun-log-go-sdk#75]
_source_: stdout

_time_: 2020-04-13T22:01:45.285849343Z

content: level=info time=2020-04-13T22:01:45.285643329Z caller=io_worker.go:74 msg="sendToServer failed" error="{\n \"httpCode\": -1,\n \"errorCode\": \"ClientError\",\n \"errorMessage\": \"stopped retrying err: {\\n \\\"httpCode\\\": 500,\\n \\\"errorCode\\\": \\\"InternalServerError\\\",\\n \\\"errorMessage\\\": \\\"internal server error,no avaliable shard\\\",\\n \\\"requestID\\\": \\\"5E94E1460400C45210C245D6\\\"\\n}: context deadline exceeded\",\n \"requestID\": \"\"\n}

**Comment by shabicheng** [comment]
你是不是只有1个Shard，建议一个logstore最好有2个shard，否则可能因为某个Shard临时不可用会报这个错误。
不过这个错误只要不持续报就没问题，producer会自动重试
