### ISSUE TITLE
按照simple_demo的方法去消费数据，日志打印 send heartbeat error

### ISSUE THREAD

**Issue by matthew188** [aliyun/aliyun-log-go-sdk#77]
level=warn time=2020-04-26T03:25:46.858718Z caller=heart_beat.go:72 msg="send heartbeat error" error="{\n    \"httpCode\": 405,\n    \"errorCode\": \"InvalidMethod\",\n    \"errorMessage\": \"invalid request method : /logstores/logxxxxx/consumergroups/\",\n    \"requestID\": \"5EA4FF3A7E87633xxxxxx\"\n}"

**Comment by god1991** [comment]
创建消费组的时候对名字有要求，但是创建失败了不会打印日志 好像是[0-9a-z] {2，32}，你换个ConsumerGroupName 试试
