### ISSUE TITLE
GetLogs

### ISSUE THREAD

**Issue by zouxinjiang** [aliyun/aliyun-log-go-sdk#78]
GetLogs接口返回值中的 x-log-count  的值是 当前查询查询到的值的数量，而不是满足当前查询条件的所有数据的数量吗。这种值有何用，我不会数一下 logs字段的长度吗？
这个接口做分页就厉害了。传 line 为100，那么x-log-count最大为100这我很无语。

**Comment by shabicheng** [comment]
查询日志总量需要用 GetHistograms
