### ISSUE TITLE
为什么使用 go-kit

### ISSUE THREAD

**Issue by mofadeyunduo** [aliyun/aliyun-log-go-sdk#95]
我不明白使用 go-kit 作为日志的原因，这看起来很奇怪。
如果需要一个日志服务，而不是微服务，为什么需要引入微服务的包？

**Comment by shabicheng** [comment]
主要是producer、consumer内部比较复杂，需要额外依赖这些库去做程序本身的日志记录

**Comment by mofadeyunduo** [comment]
我是觉得，既然没有引入其他微服务相关的内容，只用了日志，还是引用一个比较纯净的日志库比较好。go-kit 引入了 etcd，我这边引入了同为 v3 的另外一个无 bug 版本的  etcd，依赖有些问题导致这个日志服务怎么都起不来。

**Comment by shabicheng** [comment]
@mofadeyunduo 看了一下确实是这样，有没有兴趣提个PR，改掉这个go-kit的依赖？

**Comment by mofadeyunduo** [comment]
可以的，有空我会参考 http 包的日志记录方式尝试弄下

**Comment by shabicheng** [comment]
@mofadeyunduo 可以考虑使用 go.uber.org/zap，看了一下依赖还算简洁 

require (
	github.com/pkg/errors v0.8.1
	github.com/stretchr/testify v1.4.0
	go.uber.org/atomic v1.6.0
	go.uber.org/multierr v1.5.0
	golang.org/x/lint v0.0.0-20190930215403-16217165b5de
	gopkg.in/yaml.v2 v2.2.2
	honnef.co/go/tools v0.0.1-2019.2.3
)

**Comment by shabicheng** [comment]
invalid
